"""изменил поле в UserModel password на hashed_password

Revision ID: 0cf5d10f6170
Revises: 63817b2073f1
Create Date: 2026-02-22 19:08:16.051320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf5d10f6170'
down_revision: Union[str, Sequence[str], None] = '63817b2073f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # Скопировать данные из password в hashed_password
    op.execute('UPDATE users SET hashed_password = password WHERE password IS NOT NULL')
    # Теперь можно сделать NOT NULL
    op.alter_column('users', 'hashed_password', existing_type=sa.String(length=255), nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
