"""поставил роль в UserModel по умолчанию viewer

Revision ID: 289edff0d7e7
Revises: 5244a4c183dd
Create Date: 2026-02-25 23:14:15.201729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289edff0d7e7'
down_revision: Union[str, Sequence[str], None] = '5244a4c183dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
