"""Создал таблицу ComandModel

Revision ID: 3c687756274b
Revises: 0cf5d10f6170
Create Date: 2026-02-24 01:52:02.788279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c687756274b'
down_revision: Union[str, Sequence[str], None] = '0cf5d10f6170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_filled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_name'), 'commands', ['name'], unique=True)
    op.add_column('users', sa.Column('is_team_creator', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('command_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_command_id'), 'users', ['command_id'], unique=False)
    op.create_foreign_key(None, 'users', 'commands', ['command_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_command_id'), table_name='users')
    op.drop_column('users', 'command_id')
    op.drop_column('users', 'is_team_creator')
    op.drop_index(op.f('ix_commands_name'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
