"""добавил поле tsv в ComandModel

Revision ID: cfe18e865194
Revises: 289edff0d7e7
Create Date: 2026-02-26 19:12:28.309059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfe18e865194'
down_revision: Union[str, Sequence[str], None] = '289edff0d7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commands', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n        setweight(to_tsvector('english', coalesce(name, '')), 'A')\n        || setweight(to_tsvector('russian', coalesce(name, '')), 'A')\n        ", persisted=True), nullable=False))
    op.create_index('ix_commands_tsv_gin', 'commands', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commands_tsv_gin', table_name='commands', postgresql_using='gin')
    op.drop_column('commands', 'tsv')
    # ### end Alembic commands ###
